version: '3.8'

services:
  service1:
    build:
      context: ./service1
    ports:
      - "3001:3000" # Маппинг порта
    environment:
      - NODE_ENV=production

  service2:
    build:
      context: ./service2
    ports:
      - "3002:3000" # Маппинг порта
    environment:
      - NODE_ENV=production

  service3:
    build:
      context: ./service3
    ports:
      - "3003:3000" # Маппинг порта
    environment:
      - NODE_ENV=production

  service4:
    build:
      context: ./service4
    ports:
      - "3004:3000" # Маппинг порта
    environment:
      - NODE_ENV=production
