version: '3.8'

services:
  service1:
    build:
      context: ./Calendar-KisKis-back
    ports:
      - "3001:3000" # Маппинг порта
    environment:
      - NODE_ENV=production

  service2:
    build:
      context: ./kiskis-auth-back
    ports:
      - "3002:3000" # Маппинг порта
    environment:
      - NODE_ENV=production

  service4:
    build:
      context: ./yandex-maps-backend-kiskis
    ports:
      - "3004:3000" # Маппинг порта
    environment:
      - NODE_ENV=production

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auth_db
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: