version: '3'
services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"


api-service1:
    build:
      context: ./api1
      dockerfile: Dockerfile
    ports:
      - "5000:5000"


nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - api-service1

volumes:
  pgdata: